export const katexOptions = {
  macros: {
    "\\1": "\\mathbb{1}",
    "\\A": "\\mathcal{A}",
    "\\Blue": "#1",
    "\\bld": "\\mathbf{#1}",
    "\\boldb": "\\mathbf{#1}",
    "\\boldg": "\\mathbf{#1}",
    "\\boldo": "\\mathbf{#1}",
    "\\boldr": "\\mathbf{#1}",
    "\\Brown": "#1",
    "\\bs": "\\Sigma",
    "\\CharOver": "\\overset{_{#1}}{#2}",
    "\\D": "\\mathcal{D}",
    "\\de": "d_E",
    "\\E": "\\mathbb{E}",
    "\\e": "\\epsilon",
    "\\exampl": "#1",
    "\\Gold": "#1",
    "\\Green": "#1",
    "\\Grey": "#1",
    "\\H": "\\mathcal{H}",
    "\\imp": "#1",
    "\\Iset": "\\mathcal{I}",
    "\\Jcal": "\\mathcal{J}",
    "\\K": "\\mathbf{K}",
    "\\L": "\\mathcal{L}",
    "\\Lcal": "\\mathcal{L}",
    "\\lbd": "\\lambda",
    "\\Mat": "\\mathcal{#1}",
    "\\minimize": "\\operatorname*{Minimize}",
    "\\N": "\\mathbb{N}",
    "\\nicefrac": "\\frac{#1}{#2}",
    "\\Orange": "#1",
    "\\Par": "#1",
    "\\pDiff": "\\frac{\\partial #1}{\\partial #2}",
    "\\Ph": "\\mathbf{\\Phi}",
    "\\Q": "\\mathbf{Q}",
    "\\R": "\\mathbb{R}",
    "\\Real": "\\mathbb{R}",
    "\\Red": "#1",
    "\\Set": "\\mathcal{#1}",
    "\\spr": "\\mathbf f^\\top_{#1} \\mathbf f_{#2}",
    "\\T": "\\top",
    "\\term": "\\mathbf{#1}",
    "\\tran": "^{\\top}",
    "\\Tr": "\\operatorname{Tr}",
    "\\Unit": "\\mathbb{I}",
    "\\V": "\\mathbf{V}",
    "\\Vector": "{#1 \\choose #2}",
    "\\Vect": "\\vec{#1}",
    "\\Violet": "#1",
    "\\W": "\\mathbf{W}",
    "\\w": "\\mathbf{w}",
    "\\x": "\\mathbf{x}",
    "\\X": "\\mathcal{X}",
    "\\Xh": "X",
    "\\Xset": "\\mathcal{X}",
    "\\Y": "\\mathcal{Y}",
    "\\Yh": "\\mathbf{Y}",
    "\\Yhat": "\\mathbf{\\hat Y}",
    "\\Yellow": "#1",
    "\\yp": "\\hat y",
    "\\Yset": "\\mathcal{Y}",
    "\\y": "\\mathbf{y}",
    "\\z": "\\mathbf z",
    "\\argmax": "\\operatorname*{arg\\,max}",
    "\\argmin": "\\operatorname*{arg\\,min}",
  },
  strict: "ignore" as const,
  throwOnError: false,
  trust: false,
};
